# Copyright 1999-2016 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Id$

EAPI=5

# ebuild generated by hackport 0.4.6

CABAL_FEATURES="bin"
inherit haskell-cabal git-2

MY_PN="GithubNotify"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="A Notification daemon for GitHub"
HOMEPAGE="http://hackage.haskell.org/package/GithubNotify"
EGIT_REPO_URI="git://github.com/Heather/GithubNotify.git"
EGIT_MASTER="lens"

#TODO: not sure about license, tbh
LICENSE="BSD"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND="dev-haskell/aeson:=
	dev-haskell/http-conduit:=
	dev-haskell/http-types:=
	dev-haskell/lens:=
	>=dev-haskell/libnotify-0.1.1.0:=
	dev-haskell/mtl:=
	dev-haskell/resourcet:=
	dev-haskell/text:=
	dev-haskell/transformers:=
	>=dev-lang/ghc-7.10.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.22.2.0
"
