# Copyright 1999-2016 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Id$

EAPI=6

# ebuild generated by hackport 0.5

CABAL_FEATURES="bin lib profile haddock hoogle hscolour"
inherit haskell-cabal git-r3

MY_PN="shakeitoff"
MY_P="${MY_PN}-${PV}"

DESCRIPTION=""
HOMEPAGE="http://hackage.haskell.org/package/ShakeItOff"
EGIT_REPO_URI="git://github.com/Heather/Shake.It.Off.git"
SRC_URI=""

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND="dev-haskell/eternal:=[profile?]
	dev-haskell/missingh:=[profile?]
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.8
"

S="${WORKDIR}/${MY_P}"

src_configure() {
	cabal-mksetup
	haskell-cabal_src_configure
}

